### ISSUE TITLE
Transfer of large files

### ISSUE THREAD

**Issue by albu89** [Hive2Hive/Hive2Hive#113]
Hi, there seems to be an issues when transfering files bigger then 25 MBytes. Does anyboy know why? 
I get a lot of timeout errors such as: 

13:28:20.706 [NETTY-TOMP2P - worker-client/server - -3-4] WARN  net.tomp2p.connection.TimeoutFactory - channel timeout for channel Server [id: 0x3617620d, /192.33.90.67:5

In addition I noticed that files bigger then the above mentioned size result in the following error on the recipient side: 

13:28:25.198 [defaultEventExecutorGroup-2-9] WARN  o.h.c.n.messages.MessageReplyHandler - Received but denied a message. Acceptance reply = 'NO_CALLBACK_HANDLER_FOR_THIS_MESSAGE', Node ID = 'masterID'.

Thanks for your help! 

Edit: 

I just noticed that the message was denied due to the signature problems. 

[NETTY-TOMP2P - worker-client/server - -3-4] WARN  net.tomp2p.message.Decoder - wrong signature! Message:id=781343603,t=REQUEST_1,c=1,tcp

**Comment by nicoruti** [comment]
I lately improved the download of large files. Will be included in the next release.
