### ISSUE TITLE
No configuration setting found for key 'Serializer'

### ISSUE THREAD

**Issue by icaliskan** [Hive2Hive/Hive2Hive#132]
I started to use hive2hive library and want to run ConsoleClient. when i want to create connection hive2hive gives me this error.

    Selected Option: Create New Network
    Exception during menu item execution.
    
    An exception has been thrown: No configuration setting found for key 'Serializer'
    Do you want to create a new network or connect to an existing one?
    
    	[1]  Create New Network
    	[2]  Connect to Existing Network
    
    	[Q]  Back

please tell me what configuration i have to set?

**Comment by nicoruti** [comment]
It sounds as the <code>client.conf</code> file is missing. You need to have it at the same directory as the client's jar file.

**Comment by icaliskan** [comment]
i solved it that way. thanks

**Comment by nicoruti** [comment]
BTW: I just added a default config file into the jar; If the config is missing by now, the CLI should run anyway (with default values).
