### ISSUE TITLE
Whats the status of Hive2Hive?

### ISSUE THREAD

**Issue by PhilAndrew** [Hive2Hive/Hive2Hive#135]
Hi there, whats the status of this project? Looks like a good thing but no development for 5 months?

**Comment by nicoruti** [comment]
Sorry for the late answer. Ironically, it say's all to the current state of dev...

Hive2Hive started as an University project where all of the 'core' developers now graduated. Unfortunately, our jobs are keeping us busy, such that there's no real progress on Hive2Hive at the moment. Nevertheless, we're still convinced of the idea of Hive2Hive (and distributed file synchronization in general) and hope, we can contribute more in future. In addition, we hope the project gains attention by other developers / students / sympathizers which may give it the required boost. As for example with the first 'real' application <a href="http://www.peerwasp.com/">PeerWasp</a>.

Hive2Hive still not completely stable and there have to be optimizations done in the underlying TomP2P framework and of course in the Hive2Hive core.
