### ISSUE TITLE
Need advice on P2P

### ISSUE THREAD

**Issue by thirdy** [Hive2Hive/Hive2Hive#136]
Hi, I got this hobby project written in Java SE/Swing:
thirdy.github.io/blackmarket/

And I was wondering how hard would it be to have a peer to peer communication between instances of java swing applications around the world?

Also posted this question on reddit:
https://www.reddit.com/r/java/comments/3lwti0/serverless_java_se_application_communication/

**Comment by nicoruti** [comment]
Hi @thirdy 

Yes, I think it's possible. Remember that Hive2Hive is 'just' a wrapper/overlay on the <a href="https://github.com/tomp2p/TomP2P">TomP2P framework</a>, which does all the P2P stuff for us. If you want to store files / folders in an overlay network (focusing on privacy and security), Hive2Hive is the way to go. If you want to store 'pure' data into a DHT or use the overlay network for direct messaging between your swing applications, you'd probably better use TomP2P itself.

**Comment by thirdy** [comment]
@nicoruti thanks for replying

followup question, what are the infrastructure requirements in order to get a publish/subscribe 'anonymous bulletin board' up and running with TomP2P?

Will I have problems with home routers not forwarding data to the Swing application?

**Comment by nicoruti** [comment]
NAT traversal is a very difficult topic in a fully distributed network. TomP2P tries to use UPnP and NAT-PMP, but both only work if (a) the router supports it and (b) it is enabled on the router. If enabled, the router automatically sets up port-forwarding rules. All packets from the external network (Internet) to a certain port (e.g. 4622) are then forwarded to the client.

A more reliable method is using relay peers. You need to deploy one (or multiple) well-reachable relay peers (e.g. on AWS) which then forward the messages to the peers behind the NAT. Peers behind the NAT keep a long-polling TCP connection to the relay peer for the message transfer.

Further, TomP2P supports hole punching, but it is again very dependent on the router's behavior. And this does not solve the bootstrap problem (i.e. become part of the network / get to know other peers).

A publish/subscribe board is an interesting use case for decentralized P2P systems. However, it's definitely easier to implement it using a client/server architecture. P2P has the advantage that it's mostly self-organizing and scalable, as not the whole traffic flows through a centralized server.

**Comment by thirdy** [comment]
Sounds like the the answer sadly is 'no, not out of the box'. I have a fairly good idea how to setup the port forward when I was playing around with making my PC an actual server long ago. Regular users won't be happy if they had to do that.

Curious question thou, how come bit torrent is easy to install, out of the box batteries included.? it uses ports other than port 80 right?

**Comment by nicoruti** [comment]
> Sounds like the the answer sadly is 'no, not out of the box'.

Yes, there's no out of the box solution, as TomP2P is a general implementation of a DHT and Hive2Hive for file synchronization and sharing. For production use (especially NAT traversal), there's still some work to do.

> What do you think about: http://www.jgroups.org/index.html

I didn't know jgroups, but it looks like a neat project if you need a distributed / clustered solution. However, would a single server not be more simple for a publish / subscribe pattern?

> can we safely assume that most consumer routers nowadays support UPnP?

No, I don't think so. As UPnP can be a <a href="http://www.howtogeek.com/122487/htg-explains-is-upnp-a-security-risk/">security risk</a>, it is often disabled as default. Non-tech-users probably don't know how to enable it. In addition, corporate firewalls / routers are even more restrictive. Using websockets is much more reliable and works (almost) everywhere.

**Comment by rodneyrod** [comment]
Have you had a look at how Tox goes about NAT traversal and hole punching?

**Comment by thirdy** [comment]
I've given on this quest. As was noted, the answer I'm looking for is probably a server-client solution. I'll go in that direction next time I dream on pursuing this. _Right now, I got my hands full playing with ElasticSearch._

Thanks a lot for taking time explaining these stuff.

@rodneyrod Nope, but Tox looks cool
