### ISSUE TITLE
Cannot download hive2hive process framework

### ISSUE THREAD

**Issue by srivastava-utkarsh** [Hive2Hive/Hive2Hive#151]
Hi,

I've forked this project and been trying to run this project this weekend but cannot do so. It seems **process framework is not downloading due to server issues**. Here is the screenshot of my issue.
![screenshot from 2017-11-27 22-03-00](https://user-images.githubusercontent.com/10084015/33277873-dad63ee8-d3bf-11e7-848e-f70e5757909b.png)

Any help would be appreciated.

**Comment by nicoruti** [comment]
Hello

Whoops, sorry for the inconvenience! We did a reorganization of our domains and hive2hive.org was lost there. I just fixed it and it should work again.

I think it would be better to add the artifacts to Maven Central. I'm currently applying to access there.
