### ISSUE TITLE
Erasure Coding

### ISSUE THREAD

**Issue by ippes** [Hive2Hive/Hive2Hive#56]
One of the biggest challenges in p2p networks are large files. One approach could be to use erasure coding instead the usual replication mechanism. Erasure coding allows to reduce the replication rate from traditional 3-6 to approx. 1.3. But there are several questions to answer, like who is responsible for the data chunks, who calculates them etc. Another point is that TomP2P currently doesn't support erasure coding. It would require a major rebuild of our underlying p2p framework.

**Comment by nicoruti** [comment]
I rather think that this feature should be implemented in TomP2P than in Hive2Hive. I opened a ticket there (see tomp2p/TomP2P#84).
