### ISSUE TITLE
Secure Bootstrapping

### ISSUE THREAD

**Issue by Biocodr** [Hive2Hive/Hive2Hive#61]
One future enhancement i recommend is a secure bootstrap mechanism. The P2P system should be kind of "sand-boxed" where users can trust each other. This might be the case between small user bases of friends or within a business company. So in case a peer wants to bootstrap, it has to know the network password first.

**Comment by nicoruti** [comment]
Since this is rather a feature of TomP2P, I opened a ticket there.
